- id: doi:10.1021/acs.joc.6b00526
  image: https://github.com/delacernaLab/dCLabSite/blob/main/images/pubs/pentacene.gif
  authors:
   - Bikash Pal
   - Bo-Chao Lin
   - *Mark dela Cerna*
   - Chao-Ping Hsu
   - Chih-Hsu Lin
  tags:
   - Academia Sinica
