- id: doi:10.1101/2023.07.31.551065

- id: url:https://www.nsta.org/journal-college-science-teaching/journal-college-science-teaching-septemberoctober-2022/reflections

- id: doi:10.3101/1098-7096-82.1.32

- id: doi:10.1038/s41598-021-89668-5

- id: doi:10.1016/j.ejpb.2018.04.013

- id: doi:10.1021/acs.joc.6b00526
  image: https://github.com/delacernaLab/dCLabSite/blob/main/images/pubs/pentacene.gif
